import { HubConnectionBuilder } from "@microsoft/signalr";
import { Activity, ArchiveRestore, Boxes, CirclePlay, CircleStop, Download, FolderArchive, Gamepad2, LogOut, RefreshCw, Save, Settings2, TerminalSquare, Trash2, Users } from "lucide-react";
import { type ChangeEvent, type FormEvent, useCallback, useEffect, useState } from "react";
import { Button } from "./components/ui/button";
import { Card } from "./components/ui/card";

type State = "stopped" | "starting" | "running" | "stopping" | "failed";
type Status = { state: State; processId?: number; message?: string };
type Settings = { serverName: string; description: string; maxPlayers: number; visibilityPublic: boolean; autosaveMinutes: number; activeSave?: string; channel: "stable" | "experimental"; activeVersion?: string; backupIntervalHours: number; backupRetention: number; timeZone: string };
type UpdateStatus = { availableVersion?: string; checkedVersion?: string; checkedAt: string; error?: string };
type Mod = { name: string; version: string; enabled: boolean };
type PortalMod = { name: string; title?: string; summary?: string; latest_release?: { download_url?: string } };
type Tab = "overview" | "settings" | "versions" | "mods" | "saves" | "players" | "logs";
type Action = (path: string, init?: RequestInit) => Promise<boolean>;
let csrf = "";
async function api<T>(path: string, init: RequestInit = {}): Promise<T> {
  const headers = new Headers(init.headers);
  if (init.method && !["GET", "HEAD"].includes(init.method)) headers.set("X-CSRF-Token", csrf);
  if (init.body && !(init.body instanceof FormData)) headers.set("Content-Type", "application/json");
  const response = await fetch(path, { ...init, headers, credentials: "same-origin" });
  if (!response.ok) throw new Error((await response.json().catch(() => ({ error: response.statusText }))).error ?? response.statusText);
  return response.status === 204 ? undefined as T : response.json() as Promise<T>;
}

function Auth({ configured, done }: { configured: boolean; done: () => void }) {
  const [password, setPassword] = useState(""); const [code, setCode] = useState(""); const [username, setUsername] = useState(""); const [token, setToken] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); try { const result = configured ? await api<{ csrfToken: string }>("/api/auth/login", { method: "POST", body: JSON.stringify({ password }) }) : await api<{ csrfToken: string }>("/api/auth/setup", { method: "POST", body: JSON.stringify({ code, password, factorioUsername: username || null, factorioToken: token || null }) }); csrf = result.csrfToken; done(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Authentication failed."); } }
  return <main className="mx-auto flex min-h-screen max-w-md items-center px-5"><Card className="w-full space-y-5"><div className="flex items-center gap-3"><Gamepad2 className="h-9 w-9 text-yellow-400" /><div><h1 className="text-xl font-bold">Factorio Server Manager</h1><p className="text-sm text-zinc-400">{configured ? "Sign in to manage this server" : "Complete one-time setup"}</p></div></div><form onSubmit={submit} className="space-y-3">{!configured && <><label className="block text-sm">Setup code<input value={code} onChange={event => setCode(event.target.value)} required /></label><label className="block text-sm">Factorio username<input value={username} onChange={event => setUsername(event.target.value)} /></label><label className="block text-sm">Factorio token<input type="password" value={token} onChange={event => setToken(event.target.value)} /></label></>}<label className="block text-sm">Admin password<input type="password" minLength={12} value={password} onChange={event => setPassword(event.target.value)} required /></label>{error && <p className="rounded bg-red-950 p-3 text-sm text-red-300">{error}</p>}<Button className="w-full" type="submit">{configured ? "Sign in" : "Create admin account"}</Button></form></Card></main>;
}

const navigation: ReadonlyArray<[Tab, typeof Activity, string]> = [["overview", Activity, "Overview"], ["settings", Settings2, "Settings"], ["versions", Download, "Versions"], ["mods", Boxes, "Mods"], ["saves", Save, "Saves"], ["players", Users, "Players"], ["logs", TerminalSquare, "Logs"]];
const stateClasses: Record<State, string> = { running: "bg-emerald-500/20 text-emerald-300", stopped: "bg-zinc-700 text-zinc-200", starting: "bg-yellow-500/20 text-yellow-300", stopping: "bg-yellow-500/20 text-yellow-300", failed: "bg-red-500/20 text-red-300" };

export function App() {
  const [configured, setConfigured] = useState<boolean>(); const [signedIn, setSignedIn] = useState(false); const [tab, setTab] = useState<Tab>("overview"); const [status, setStatus] = useState<Status>(); const [settings, setSettings] = useState<Settings>(); const [logs, setLogs] = useState<string[]>([]); const [error, setError] = useState("");
  const refresh = useCallback(async () => { try { const [nextStatus, nextSettings, nextLogs] = await Promise.all([api<Status>("/api/status"), api<Settings>("/api/settings"), api<string[]>("/api/logs")]); setStatus(nextStatus); setSettings(nextSettings); setLogs(nextLogs); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load server state."); } }, []);
  useEffect(() => { api<{ configured: boolean }>("/api/auth/status").then(result => { setConfigured(result.configured); if (result.configured) api<{ csrfToken: string }>("/api/auth/me").then(me => { csrf = me.csrfToken; setSignedIn(true); }).catch(() => undefined); }).catch(() => setConfigured(false)); }, []);
  useEffect(() => { if (!signedIn) return; void refresh(); const connection = new HubConnectionBuilder().withUrl("/hubs/status").withAutomaticReconnect().build(); connection.on("status", setStatus); connection.on("log", (line: string) => setLogs(current => [...current.slice(-499), `${new Date().toISOString()} ${line}`])); void connection.start(); return () => { void connection.stop(); }; }, [signedIn, refresh]);
  const action: Action = async (path, init = { method: "POST" }) => { try { setError(""); await api(path, init); await refresh(); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : "Request failed."); return false; } };
  if (configured === undefined) return <main className="p-8 text-zinc-400">Loading…</main>;
  if (!signedIn) return <Auth configured={configured} done={() => setSignedIn(true)} />;
  const title = navigation.find(item => item[0] === tab)?.[2];
  return <div className="min-h-screen md:grid md:grid-cols-[15rem_1fr]"><aside className="border-b border-zinc-800 bg-zinc-900/50 p-4 md:min-h-screen md:border-b-0 md:border-r"><div className="mb-7 flex items-center gap-2 font-bold"><Gamepad2 className="text-yellow-400" />Factorio Manager</div><nav className="flex gap-2 overflow-x-auto md:flex-col">{navigation.map(([id, Icon, label]) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-3 rounded-md px-3 py-2 text-sm ${tab === id ? "bg-yellow-400 text-zinc-950" : "text-zinc-300 hover:bg-zinc-800"}`}><Icon size={17} />{label}</button>)}</nav><Button variant="outline" className="mt-8 w-full" onClick={() => void action("/api/auth/logout").then(() => { csrf = ""; setSignedIn(false); })}><LogOut size={16} className="mr-2" />Sign out</Button></aside><main className="mx-auto w-full max-w-6xl p-5 md:p-8"><header className="mb-7 flex items-center justify-between"><div><h1 className="text-2xl font-bold">{title}</h1><p className="text-sm text-zinc-400">One container, one Factorio server</p></div>{status && <span className={`rounded-full px-3 py-1 text-xs font-semibold uppercase ${stateClasses[status.state]}`}>{status.state}</span>}</header>{error && <p className="mb-5 rounded bg-red-950 p-3 text-sm text-red-300">{error}</p>}{tab === "overview" && <Overview status={status} settings={settings} action={action} />}{tab === "settings" && settings && <SettingsPage settings={settings} action={action} />}{tab === "versions" && <Versions settings={settings} action={action} />}{tab === "mods" && <Mods action={action} />}{tab === "saves" && <Saves action={action} />}{tab === "players" && <Players action={action} />}{tab === "logs" && <Card><pre className="max-h-[65vh] overflow-auto whitespace-pre-wrap break-words font-mono text-xs text-zinc-300">{logs.join("\n") || "No server output yet."}</pre></Card>}</main></div>;
}

function Overview({ status, settings, action }: { status?: Status; settings?: Settings; action: Action }) { return <div className="grid gap-5 lg:grid-cols-3"><Card className="lg:col-span-2"><h2 className="mb-1 text-lg font-semibold">{settings?.serverName ?? "Server"}</h2><p className="mb-5 text-sm text-zinc-400">{settings?.description}</p><div className="flex flex-wrap gap-3"><Button onClick={() => void action("/api/control/start")} disabled={status?.state === "running" || status?.state === "starting"}><CirclePlay className="mr-2" size={17} />Start</Button><Button variant="destructive" onClick={() => void action("/api/control/stop")} disabled={status?.state !== "running"}><CircleStop className="mr-2" size={17} />Stop</Button><Button variant="secondary" onClick={() => void action("/api/control/restart")} disabled={status?.state !== "running"}>Restart</Button></div>{status?.message && <p className="mt-4 text-sm text-red-300">{status.message}</p>}</Card><Card><h2 className="mb-3 font-semibold">Runtime</h2><dl className="space-y-2 text-sm"><div className="flex justify-between"><dt className="text-zinc-400">Version</dt><dd>{settings?.activeVersion ?? "Not selected"}</dd></div><div className="flex justify-between"><dt className="text-zinc-400">Save</dt><dd>{settings?.activeSave ?? "Not selected"}</dd></div><div className="flex justify-between"><dt className="text-zinc-400">Process</dt><dd>{status?.processId ?? "—"}</dd></div></dl></Card></div>; }

function SettingsPage({ settings, action }: { settings: Settings; action: Action }) { const [draft, setDraft] = useState(settings); const field = (key: keyof Settings) => ({ value: String(draft[key] ?? ""), onChange: (event: ChangeEvent<HTMLInputElement>) => setDraft({ ...draft, [key]: event.target.type === "number" ? Number(event.target.value) : event.target.value }) }); return <form onSubmit={event => { event.preventDefault(); void action("/api/settings", { method: "PUT", body: JSON.stringify(draft) }); }} className="grid gap-5 lg:grid-cols-2"><Card className="space-y-3"><h2 className="font-semibold">Server</h2><label className="block text-sm">Server name<input {...field("serverName")} /></label><label className="block text-sm">Description<input {...field("description")} /></label><label className="block text-sm">Max players (0 = unlimited)<input type="number" {...field("maxPlayers")} /></label><label className="block text-sm">Autosave minutes<input type="number" {...field("autosaveMinutes")} /></label></Card><Card className="space-y-3"><h2 className="font-semibold">Maintenance</h2><label className="block text-sm">Backup interval (hours)<input type="number" {...field("backupIntervalHours")} /></label><label className="block text-sm">Backup retention<input type="number" {...field("backupRetention")} /></label><label className="block text-sm">Timezone<input {...field("timeZone")} /></label><label className="flex items-center gap-2 text-sm"><input className="w-auto" type="checkbox" checked={draft.visibilityPublic} onChange={event => setDraft({ ...draft, visibilityPublic: event.target.checked })} />List publicly</label></Card><div className="lg:col-span-2"><Button type="submit"><Settings2 className="mr-2" size={16} />Save settings</Button></div></form>; }

function Versions({ settings, action }: { settings?: Settings; action: Action }) {
  const [version, setVersion] = useState(settings?.activeVersion ?? "");
  const [channel, setChannel] = useState<"stable" | "experimental">(settings?.channel ?? "stable");
  const [cached, setCached] = useState<string[]>([]);
  const [update, setUpdate] = useState<UpdateStatus>();
  const [checking, setChecking] = useState(false);
  const load = useCallback(async () => {
    const [nextCached, nextUpdate] = await Promise.all([api<string[]>("/api/versions"), api<UpdateStatus | null>("/api/updates")]);
    setCached(nextCached); setUpdate(nextUpdate ?? undefined);
  }, []);
  useEffect(() => { void load(); }, [load]);
  async function checkForUpdates() {
    setChecking(true);
    try { setUpdate(await api<UpdateStatus>("/api/updates/check", { method: "POST" })); } finally { setChecking(false); }
  }
  const checkedAt = update?.checkedAt ? new Date(update.checkedAt).toLocaleString() : "never";
  return <div className="grid gap-5 lg:grid-cols-2">
    <Card className="space-y-3">
      <div className="flex items-center justify-between"><h2 className="font-semibold">Version</h2><Button size="sm" variant="outline" onClick={() => void checkForUpdates()} disabled={checking || !settings?.activeVersion}><RefreshCw className={`mr-2 ${checking ? "animate-spin" : ""}`} size={15} />{checking ? "Checking…" : "Check for updates"}</Button></div>
      {update?.availableVersion ? <div className="rounded border border-yellow-500/50 bg-yellow-500/10 p-3 text-sm text-yellow-200"><p className="font-semibold">Update available: {update.availableVersion}</p><p className="mt-1 text-yellow-100/70">Automatic updates are disabled. Download and apply it when ready.</p></div> : update?.error ? <p className="rounded bg-red-950 p-3 text-sm text-red-300">Update check failed: {update.error}</p> : <p className="text-xs text-zinc-500">Last checked: {checkedAt}</p>}
      <select value={channel} onChange={event => setChannel(event.target.value as typeof channel)}><option value="stable">Stable</option><option value="experimental">Experimental</option></select><input placeholder="e.g. 2.0.67" value={version} onChange={event => setVersion(event.target.value)} /><Button onClick={() => void action(`/api/versions/download/${channel}/${encodeURIComponent(version)}`).then(load)} disabled={!version}><Download className="mr-2" size={16} />Download</Button><Button variant="secondary" onClick={() => void action("/api/versions/apply", { method: "POST", body: JSON.stringify({ version, channel }) }).then(load)} disabled={!version}>Apply selected version</Button>
    </Card>
    <Card><h2 className="mb-3 font-semibold">Cached versions</h2><div className="space-y-2">{cached.length ? cached.map(item => <button key={item} className={`block w-full rounded border px-3 py-2 text-left text-sm ${item === version ? "border-yellow-400" : "border-zinc-700"}`} onClick={() => setVersion(item)}>{item}</button>) : <p className="text-sm text-zinc-400">No server versions downloaded.</p>}</div></Card>
  </div>;
}

function Mods({ action }: { action: Action }) { const [query, setQuery] = useState(""); const [results, setResults] = useState<PortalMod[]>([]); const [installed, setInstalled] = useState<Mod[]>([]); const load = useCallback(() => { void api<Mod[]>("/api/mods").then(setInstalled); }, []); useEffect(load, [load]); async function search(event: FormEvent) { event.preventDefault(); try { setResults((await api<{ results?: PortalMod[] }>(`/api/mods/search?query=${encodeURIComponent(query)}`)).results ?? []); } catch { setResults([]); } } return <div className="grid gap-5 lg:grid-cols-2"><Card className="space-y-3"><h2 className="font-semibold">Mod Portal</h2><form onSubmit={search} className="flex gap-2"><input placeholder="Search mods" value={query} onChange={event => setQuery(event.target.value)} /><Button type="submit">Search</Button></form>{results.map(mod => <div key={mod.name} className="rounded border border-zinc-800 p-3"><p className="font-medium">{mod.title ?? mod.name}</p><p className="mb-2 text-xs text-zinc-400">{mod.summary}</p><Button size="sm" disabled={!mod.latest_release?.download_url} onClick={() => void action("/api/mods/install", { method: "POST", body: JSON.stringify({ name: mod.name, downloadUrl: mod.latest_release?.download_url, enabled: true }) }).then(load)}>Install</Button></div>)}</Card><Card><h2 className="mb-3 font-semibold">Installed</h2>{installed.length ? <div className="space-y-2">{installed.map(mod => <div key={mod.name} className="flex items-center justify-between rounded border border-zinc-800 p-3 text-sm"><span>{mod.name} <span className="text-zinc-500">{mod.version}</span></span><Button size="sm" variant={mod.enabled ? "secondary" : "outline"} onClick={() => void action(`/api/mods/${encodeURIComponent(mod.name)}/enabled/${!mod.enabled}`).then(load)}>{mod.enabled ? "Disable" : "Enable"}</Button></div>)}</div> : <p className="text-sm text-zinc-400">No mods installed.</p>}</Card></div>; }

function Saves({ action }: { action: Action }) { const [file, setFile] = useState<File>(); const [name, setName] = useState(""); const [saves, setSaves] = useState<string[]>([]); const [backups, setBackups] = useState<string[]>([]); const load = useCallback(() => { void Promise.all([api<string[]>("/api/saves"), api<string[]>("/api/backups")]).then(([nextSaves, nextBackups]) => { setSaves(nextSaves); setBackups(nextBackups); }); }, []); useEffect(load, [load]); async function upload() { if (!file) return; const form = new FormData(); form.append("file", file); if (await action("/api/saves/upload", { method: "POST", body: form })) load(); } return <div className="grid gap-5 lg:grid-cols-2"><Card className="space-y-3"><h2 className="font-semibold">Saves</h2><div className="flex gap-2"><input placeholder="New map name" value={name} onChange={event => setName(event.target.value)} /><Button variant="secondary" onClick={() => void action("/api/saves/create", { method: "POST", body: JSON.stringify({ name }) }).then(load)} disabled={!name}>Create</Button></div><input type="file" accept=".zip" onChange={event => setFile(event.target.files?.[0])} /><Button onClick={() => void upload()} disabled={!file}><Save className="mr-2" size={16} />Upload</Button><div className="space-y-2">{saves.map(save => <div key={save} className="flex items-center justify-between rounded border border-zinc-800 p-2 text-sm"><span>{save}</span><Button size="sm" variant="outline" onClick={() => void action(`/api/saves/select/${encodeURIComponent(save)}`)}>Use</Button></div>)}</div></Card><Card><h2 className="mb-3 font-semibold">Backups</h2><Button variant="secondary" onClick={() => void action("/api/saves/backup").then(load)}><FolderArchive className="mr-2" size={16} />Create backup</Button><div className="mt-4 space-y-2">{backups.map(backup => <div key={backup} className="flex items-center justify-between rounded border border-zinc-800 p-2 text-sm"><span className="truncate pr-2">{backup}</span><Button size="sm" variant="outline" onClick={() => void action(`/api/backups/restore/${encodeURIComponent(backup)}`).then(load)}><ArchiveRestore size={15} /></Button></div>)}</div></Card></div>; }

function Players({ action }: { action: Action }) { const [kind, setKind] = useState("admins"); const [name, setName] = useState(""); const [players, setPlayers] = useState<string[]>([]); const load = useCallback(() => { void api<string[]>(`/api/players/${kind}`).then(setPlayers); }, [kind]); useEffect(load, [load]); return <Card className="max-w-xl space-y-4"><h2 className="font-semibold">Player lists</h2><select value={kind} onChange={event => setKind(event.target.value)}><option value="admins">Admins</option><option value="whitelist">Whitelist</option><option value="bans">Bans</option></select><div className="flex gap-2"><input placeholder="Factorio player name" value={name} onChange={event => setName(event.target.value)} /><Button onClick={() => void action(`/api/players/${kind}`, { method: "POST", body: JSON.stringify({ playerName: name }) }).then(success => { if (success) { setName(""); load(); } })} disabled={!name}>Add</Button></div><div className="space-y-2">{players.map(player => <div key={player} className="flex items-center justify-between rounded border border-zinc-800 p-3 text-sm"><span>{player}</span><Button size="sm" variant="destructive" onClick={() => void action(`/api/players/${kind}/${encodeURIComponent(player)}`, { method: "DELETE" }).then(load)}><Trash2 size={15} /></Button></div>)}{!players.length && <p className="text-sm text-zinc-400">This list is empty.</p>}</div></Card>; }
